server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /tour-image-proxy/ {
        proxy_pass https://tong.visitkorea.or.kr/;
        proxy_ssl_server_name on;
        proxy_ssl_name tong.visitkorea.or.kr;
        proxy_set_header Host tong.visitkorea.or.kr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
