/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginSuccessRouteImport } from './routes/login-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authenticationRouteRouteImport } from './routes/(authentication)/route'
import { Route as authenticationIndexRouteImport } from './routes/(authentication)/index'
import { Route as authenticationMyRouteImport } from './routes/(authentication)/my'
import { Route as authenticationCourseRouteImport } from './routes/(authentication)/course'
import { Route as authenticationNoteIndexRouteImport } from './routes/(authentication)/note/index'
import { Route as authenticationNoteCourseIdRouteImport } from './routes/(authentication)/note/$courseId'

const LoginSuccessRoute = LoginSuccessRouteImport.update({
  id: '/login-success',
  path: '/login-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticationRouteRoute = authenticationRouteRouteImport.update({
  id: '/(authentication)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticationIndexRoute = authenticationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticationRouteRoute,
} as any)
const authenticationMyRoute = authenticationMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => authenticationRouteRoute,
} as any)
const authenticationCourseRoute = authenticationCourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => authenticationRouteRoute,
} as any)
const authenticationNoteIndexRoute = authenticationNoteIndexRouteImport.update({
  id: '/note/',
  path: '/note/',
  getParentRoute: () => authenticationRouteRoute,
} as any)
const authenticationNoteCourseIdRoute =
  authenticationNoteCourseIdRouteImport.update({
    id: '/note/$courseId',
    path: '/note/$courseId',
    getParentRoute: () => authenticationRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/login-success': typeof LoginSuccessRoute
  '/course': typeof authenticationCourseRoute
  '/my': typeof authenticationMyRoute
  '/': typeof authenticationIndexRoute
  '/note/$courseId': typeof authenticationNoteCourseIdRoute
  '/note/': typeof authenticationNoteIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/login-success': typeof LoginSuccessRoute
  '/course': typeof authenticationCourseRoute
  '/my': typeof authenticationMyRoute
  '/': typeof authenticationIndexRoute
  '/note/$courseId': typeof authenticationNoteCourseIdRoute
  '/note': typeof authenticationNoteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authentication)': typeof authenticationRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/login-success': typeof LoginSuccessRoute
  '/(authentication)/course': typeof authenticationCourseRoute
  '/(authentication)/my': typeof authenticationMyRoute
  '/(authentication)/': typeof authenticationIndexRoute
  '/(authentication)/note/$courseId': typeof authenticationNoteCourseIdRoute
  '/(authentication)/note/': typeof authenticationNoteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/login-success'
    | '/course'
    | '/my'
    | '/'
    | '/note/$courseId'
    | '/note/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/login-success'
    | '/course'
    | '/my'
    | '/'
    | '/note/$courseId'
    | '/note'
  id:
    | '__root__'
    | '/(authentication)'
    | '/login'
    | '/login-success'
    | '/(authentication)/course'
    | '/(authentication)/my'
    | '/(authentication)/'
    | '/(authentication)/note/$courseId'
    | '/(authentication)/note/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticationRouteRoute: typeof authenticationRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginSuccessRoute: typeof LoginSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-success': {
      id: '/login-success'
      path: '/login-success'
      fullPath: '/login-success'
      preLoaderRoute: typeof LoginSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)': {
      id: '/(authentication)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)/': {
      id: '/(authentication)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticationIndexRouteImport
      parentRoute: typeof authenticationRouteRoute
    }
    '/(authentication)/my': {
      id: '/(authentication)/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof authenticationMyRouteImport
      parentRoute: typeof authenticationRouteRoute
    }
    '/(authentication)/course': {
      id: '/(authentication)/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof authenticationCourseRouteImport
      parentRoute: typeof authenticationRouteRoute
    }
    '/(authentication)/note/': {
      id: '/(authentication)/note/'
      path: '/note'
      fullPath: '/note/'
      preLoaderRoute: typeof authenticationNoteIndexRouteImport
      parentRoute: typeof authenticationRouteRoute
    }
    '/(authentication)/note/$courseId': {
      id: '/(authentication)/note/$courseId'
      path: '/note/$courseId'
      fullPath: '/note/$courseId'
      preLoaderRoute: typeof authenticationNoteCourseIdRouteImport
      parentRoute: typeof authenticationRouteRoute
    }
  }
}

interface authenticationRouteRouteChildren {
  authenticationCourseRoute: typeof authenticationCourseRoute
  authenticationMyRoute: typeof authenticationMyRoute
  authenticationIndexRoute: typeof authenticationIndexRoute
  authenticationNoteCourseIdRoute: typeof authenticationNoteCourseIdRoute
  authenticationNoteIndexRoute: typeof authenticationNoteIndexRoute
}

const authenticationRouteRouteChildren: authenticationRouteRouteChildren = {
  authenticationCourseRoute: authenticationCourseRoute,
  authenticationMyRoute: authenticationMyRoute,
  authenticationIndexRoute: authenticationIndexRoute,
  authenticationNoteCourseIdRoute: authenticationNoteCourseIdRoute,
  authenticationNoteIndexRoute: authenticationNoteIndexRoute,
}

const authenticationRouteRouteWithChildren =
  authenticationRouteRoute._addFileChildren(authenticationRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticationRouteRoute: authenticationRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginSuccessRoute: LoginSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
