/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authenticationRouteRouteImport } from './routes/(authentication)/route'
import { Route as authenticationIndexRouteImport } from './routes/(authentication)/index'
import { Route as authenticationNoteRouteImport } from './routes/(authentication)/note'
import { Route as authenticationMyRouteImport } from './routes/(authentication)/my'
import { Route as authenticationCourseRouteImport } from './routes/(authentication)/course'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticationRouteRoute = authenticationRouteRouteImport.update({
  id: '/(authentication)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticationIndexRoute = authenticationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticationRouteRoute,
} as any)
const authenticationNoteRoute = authenticationNoteRouteImport.update({
  id: '/note',
  path: '/note',
  getParentRoute: () => authenticationRouteRoute,
} as any)
const authenticationMyRoute = authenticationMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => authenticationRouteRoute,
} as any)
const authenticationCourseRoute = authenticationCourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => authenticationRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/course': typeof authenticationCourseRoute
  '/my': typeof authenticationMyRoute
  '/note': typeof authenticationNoteRoute
  '/': typeof authenticationIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/course': typeof authenticationCourseRoute
  '/my': typeof authenticationMyRoute
  '/note': typeof authenticationNoteRoute
  '/': typeof authenticationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authentication)': typeof authenticationRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(authentication)/course': typeof authenticationCourseRoute
  '/(authentication)/my': typeof authenticationMyRoute
  '/(authentication)/note': typeof authenticationNoteRoute
  '/(authentication)/': typeof authenticationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/course' | '/my' | '/note' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/course' | '/my' | '/note' | '/'
  id:
    | '__root__'
    | '/(authentication)'
    | '/login'
    | '/(authentication)/course'
    | '/(authentication)/my'
    | '/(authentication)/note'
    | '/(authentication)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticationRouteRoute: typeof authenticationRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)': {
      id: '/(authentication)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)/': {
      id: '/(authentication)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticationIndexRouteImport
      parentRoute: typeof authenticationRouteRoute
    }
    '/(authentication)/note': {
      id: '/(authentication)/note'
      path: '/note'
      fullPath: '/note'
      preLoaderRoute: typeof authenticationNoteRouteImport
      parentRoute: typeof authenticationRouteRoute
    }
    '/(authentication)/my': {
      id: '/(authentication)/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof authenticationMyRouteImport
      parentRoute: typeof authenticationRouteRoute
    }
    '/(authentication)/course': {
      id: '/(authentication)/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof authenticationCourseRouteImport
      parentRoute: typeof authenticationRouteRoute
    }
  }
}

interface authenticationRouteRouteChildren {
  authenticationCourseRoute: typeof authenticationCourseRoute
  authenticationMyRoute: typeof authenticationMyRoute
  authenticationNoteRoute: typeof authenticationNoteRoute
  authenticationIndexRoute: typeof authenticationIndexRoute
}

const authenticationRouteRouteChildren: authenticationRouteRouteChildren = {
  authenticationCourseRoute: authenticationCourseRoute,
  authenticationMyRoute: authenticationMyRoute,
  authenticationNoteRoute: authenticationNoteRoute,
  authenticationIndexRoute: authenticationIndexRoute,
}

const authenticationRouteRouteWithChildren =
  authenticationRouteRoute._addFileChildren(authenticationRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticationRouteRoute: authenticationRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
